//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ahorcado.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ahorcado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _492snake_100855 {
            get {
                object obj = ResourceManager.GetObject("492snake_100855", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book_19742 {
            get {
                object obj = ResourceManager.GetObject("book_19742", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crown_king_queen_icon_161518 {
            get {
                object obj = ResourceManager.GetObject("crown_king_queen_icon_161518", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gem_pendant_39134 {
            get {
                object obj = ResourceManager.GetObject("gem-pendant_39134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LONGBOTTOM  
        ///MCGONAGALL  
        ///LESTRANGE  
        ///DIGGORY  
        ///LOVEGOOD  
        ///MALFOY  
        ///WEASLEY  
        ///GRANGER  
        ///POTTER  
        ///BLACK  
        ///DELACOUR  
        ///MAXIME  
        ///KARKAROV  
        ///KRUM  
        ///RIDDLE  
        ///DUMBLEDORE  
        ///UMBRIDGE  
        ///GRINDELWALD  
        ///TRELAWNEY  
        ///POMFREY  
        ///PETTIGREW  
        ///DURSLEY  
        ///GODRIC  
        ///ANIMAGO  
        ///COLAGUSANO  
        ///CORNAMENTA  
        ///LUNATICO  
        ///CANUTO  
        ///MORTIFAGOS  
        ///MUGGLES  
        ///SQUIB  
        ///INFERIUS  
        ///BOGGART  
        ///DEMENTOR  
        ///FENIX  
        ///BASILISCO  
        ///CENTAURO  
        ///HIPOGRIFO  
        ///ESCARBATO  
        ///THESTRAL  
        ///NARGLES  
        ///ACROMANTULA  
        ///GRINDYLOW  
        ///UNICO [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string harryPotter {
            get {
                return ResourceManager.GetString("harryPotter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_05_harry_potter_colour_death_eater_tattoo_2730318_88128 {
            get {
                object obj = ResourceManager.GetObject("if-05-harry-potter-colour-death-eater-tattoo-2730318_88128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_06_harry_potter_colour_sorting_hat_2730319_88134 {
            get {
                object obj = ResourceManager.GetObject("if-06-harry-potter-colour-sorting-hat-2730319_88134", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_08_harry_potter_colour_chamber_of_secrets_key_2730321_88178 {
            get {
                object obj = ResourceManager.GetObject("if-08-harry-potter-colour-chamber-of-secrets-key-2730321_88178", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_11_harry_potter_colour_quill_2730324_88144 {
            get {
                object obj = ResourceManager.GetObject("if-11-harry-potter-colour-quill-2730324_88144", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon if_12_harry_potter_colour_harrys_lightning_scar_2730325_88172 {
            get {
                object obj = ResourceManager.GetObject("if_12_harry_potter_colour_harrys_lightning_scar_2730325_88172", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_21_harry_potter_colour_glasses_and_scar_2730334_881261 {
            get {
                object obj = ResourceManager.GetObject("if-21-harry-potter-colour-glasses-and-scar-2730334_881261", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_27_harry_potter_colour_triwizard_cup_27303391_88129 {
            get {
                object obj = ResourceManager.GetObject("if-27-harry-potter-colour-triwizard-cup-27303391_88129", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_34_harry_potter_colour_horcrux_ring_2730345_88152 {
            get {
                object obj = ResourceManager.GetObject("if-34-harry-potter-colour-horcrux-ring-2730345_88152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_37_harry_potter_colour_spectrespecs_2730311_88140__1_ {
            get {
                object obj = ResourceManager.GetObject("if-37-harry-potter-colour-spectrespecs-2730311_88140 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_45_harry_potter_colour_hufflepuff_cup_2730355_88164 {
            get {
                object obj = ResourceManager.GetObject("if-45-harry-potter-colour-hufflepuff-cup-2730355_88164", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap relicario2 {
            get {
                object obj = ResourceManager.GetObject("relicario2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
